# Site Settings
name: iamkulbhushansingh blog
description: just my experiences in open source :)
baseurl: ""
url : "https://iamkulbhushansingh.github.io"

# Blog Settings
theme_settings :
  title : Kulbhushan Singh -Algorithm
  favicon : assets/faviconn.ico

  # Profile Settings
  profile :
    image : assets/img/dp.png
    username : Kulbhushan Singh
    description : Hey there! Stalker,have a good day :smile
    experience :
      - start : JUNE 2018 
        end : Present
        experience : BCA
    skills : 
      - skill : HTML5 & CSS
        value : 70 # Percent value
      - skill : Python
        value : 60
      - skill : C++
        value : 80
      - skill : Java
        value : 70
      - skill : MySql
        value : 60

  # Icons
  icons :
    email:  iamkulbhushansingh@gmail.com
    linkedin: https://www.linkedin.com/in/kulbhushan-singh-0b5204196/ # Full URL 
    github: iamkulbhushansingh
    gitlab: 
    bitbucket: 
    google_plus:
    twitter: 
    youtube:
    facebook: 
    instagram: im_rajput.py

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
