# Site Settings
baseurl: ""
url : "https://naye0ng.github.io"

# Blog Settings
theme_settings :
  title : Grape Theme
  favicon : assets/favicon.ico

  # Profile Settings
  profile :
    image : assets/img/smile.png
    username : Nayeong Kim
    description : creator of Grape-Theme! Grape-Theme is my first jekyll theme and you can customize this theme easily.
    experience :
      - start : 2017-05-03
        end : 2018-05-06
        experience : company name, title
    skills : 
      - skill : HTML5 & CSS
        value : 85  # Percent value
        
  # Icons
  icons :
    email:  # Full email address, e.g. "sample@google.com"
    linkedin:  # Full URL 
    github: naye0ng
    gitlab: 
    bitbucket: 
    google_plus:
    twitter:
    youtube:
    facebook:
    instagram:

  # Disqus
  disqus_shortname :

# Pagination
paginate: 5
paginate_path: "blog/page:num"

# Build Ssttings
sass:
  sass_dir: _sass
  style: :compressed
gems: [jekyll-paginate]
bootstrap:
  assets: true
